services:
  - type: web
    name: employee-app
    env: python
    buildCommand: ""
    startCommand: gunicorn backend:app
    envVars:
      - key: DATABASE_URL
        value: your_database_url_here
    build:
    environment:
      pythonVersion: 3.11.9